export enum ActionVerifyOtpEnum {
  VERIFY_OTP = 'VERIFY_OTP',
  VERIFY_PASSWORD = 'VERIFY_PASSWORD',
  CREATE_PATIENT = 'CREATE_PATIENT',
  CREATE_PASSWORD = 'CREATE_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD',
}
