export enum PaymentMethodEnum {
  LOCAL = 'LOCAL',
  INTERNATIONAL = 'INTERNATIONAL',
  PAYOO_AT_STORE = 'PAYOO_AT_STORE',
  MOMO = 'MOMO',
  QR_CODE = 'QR_CODE',
  SMS = 'SMS',
  PAY_AT_SERVICE = 'PAY_AT_SERVICE',
}
