export enum PayooPaymentMethodEnum {
  E_WALLET = 'E_WALLET',
  INTERNATIONAL_CARD = 'INTERNATIONAL_CARD',
  INTERNAL_CARD = 'INTERNAL_CARD',
  PAY_AT_STORE = 'PAY_AT_STORE ',
  QR_CODE = 'QR_CODE ',
  ZALO_PAY = 'ZALO_PAY ',
  MOMO = 'MOMO',
}
