export const APPOINTMENT_STATUS = {
  ALL: 'ALL',
  CONFIRMED: 'CONFIRMED',
  UNCONFIRMED: 'UNCONFIRMED',
  CANCELLED: 'CANCELLED',
  ARRIVED: 'ARRIVED',
  PLACED: 'PLACED',
  WAIT_FOR_PLACING: 'WAIT_FOR_PLACING',
  REJECT: 'REJECT',
  END: 'END',
  MISSED: 'MISSED',
  FAILED: 'FAILED',
};
