export const Constant = {
  messageStatus: {
    success: 'success',
    info: 'info',
    warn: 'warn',
    error: 'error',
  },
  auths: {
    isLoginIn: 'crm-loggedIn',
    token: 'crm-token',
    userId: 'crm-userId',
    userName: 'crm-userName',
    currentUser: 'crm-currentUser',
    fullName: 'crm-fullName',
    tokenFirebase: 'crm-tokenFirebase',
    user: 'user',
  },
  classes: {
    includes: {
      province: {
        country: 'Country',
      },
      district: {
        province: 'Province',
      },
      ward: {
        district: 'District',
      },
      hub: {
        district: 'District',
        ward: 'Ward',
        centerHub: 'CenterHub',
        poHub: 'PoHub',
      },
      user: {
        department: 'Department',
        role: 'Role',
        hub: 'Hub',
      },
      shipment: {
        cusDepartment: 'CusDepartment',
        sender: 'Sender',
        service: 'Service',
        fromHub: 'FromHub',
        toHub: 'ToHub',
        fromHubRouting: 'FromHubRouting',
        toHubRouting: 'ToHubRouting',
        fromWard: 'FromWard',
        fromDistrict: 'FromWard.District',
        fromProvince: 'FromWard.District.Province',
        toWard: 'ToWard',
        toDistrict: 'ToWard.District',
        // toDistrict: "ToDistrict",
        toProvince: 'ToProvince',
        shipmentStatus: 'ShipmentStatus',
        package: 'Package',
        pickUser: 'PickUser',
        deliverUser: 'DeliverUser',
        transferUser: 'TransferUser',
        returnUser: 'ReturnUser',
        transferReturnUser: 'TransferReturnUser',
        receiveHub: 'ReceiveHub',
        currentHub: 'CurrentHub',
        currentEmp: 'CurrentEmp',
        paymentType: 'PaymentType',
        serviceDVGT: 'ServiceDVGT',
        weight: 'Weight',
        totalBox: 'TotalBox',
        structure: 'Structure',
        companyFrom: 'CompanyFrom',
        companyTo: 'CompanyTo',
        shipmentServiceDVGTs: 'ShipmentServiceDVGTs',
        serviceDVGTIds: 'ServiceDVGTIds',
        boxes: 'Boxes',
        tpl: 'TPL',
        listGoods: 'ListGoods',
        requestShipment: 'RequestShipment',
      },
      customer: {
        province: 'Province',
        district: 'District',
        ward: 'Ward',
        paymentType: 'PaymentType',
        customerPriceList: 'CustomerPriceList',
        hub: 'Hub',
        accountingUser: 'AccountingUser',
        salesUser: 'SalesUser',
        supportUser: 'SupportUser',
      },
      serviceDVGTPrice: {
        formula: 'Formula',
        serviceDVGT: 'ServiceDVGT',
        priceListDVGT: 'PriceListDVGT',
        calculateBy: 'CalculateBy',
      },
      priceServiceDetail: {
        priceService: 'PriceService',
        area: 'Area',
        weight: 'Weight',
      },
      priceService: {
        priceList: 'PriceList',
        service: 'Service',
        areaGroup: 'AreaGroup',
        weightGroup: 'WeightGroup',
      },
      priceRemoteArea: {
        priceService: 'PriceService',
        areaGroup: 'AreaGroup',
        weightGroup: 'WeightGroup',
      },
      priceList: {
        hub: 'Hub',
        priceListDVGT: 'PriceListDVGT',
      },
      packagePriceList: {
        packType: 'PackType',
        formula: 'Formula',
        calculateBy: 'CalculateBy',
      },
      weight: {
        formula: 'Formula',
        weightGroup: 'WeightGroup',
        structure: 'Structure',
      },
      areaGroup: {
        hub: 'Hub',
      },
      area: {
        areaGroup: 'AreaGroup',
        province: 'Province',
        district: 'District',
      },
      listGoods: {
        createdByHub: 'CreatedByHub',
        listGoodsTypeId: 'ListGoodsTypeId',
        listGoodsType: 'ListGoodsType',
        numPrint: 'NumPrint',
        createdHub: 'CreatedHub',
        createdWhen: 'CreatedWhen',
        tpl: 'TPL',
        listGoodsStatus: 'ListGoodsStatus',
        fromHub: 'FromHub',
        toHub: 'ToHub',
        transportType: 'TransportType',
        emp: 'Emp',
      },
      listReceiptMoney: {
        fromHub: 'FromHub',
        toHub: 'ToHub',
        paidByEmp: 'PaidByEmp',
        userCreated: 'UserCreated',
        userModified: 'UserModified',
        listReceiptMoneyStatus: 'ListReceiptMoneyStatus',
        listReceiptMoneyType: 'ListReceiptMoneyType',
      },
      listCustomerPayment: {
        hubCreated: 'HubCreated',
        customer: 'Customer',
        userCreated: 'UserCreated',
        userModified: 'UserModified',
        listCustomerPaymentType: 'ListCustomerPaymentType',
      },
      transportType: {
        tplTransportTypes: 'TPLTransportTypes.TPL',
      },
      provinceCode: {
        customer: 'Customer',
        hub: 'Hub',
        user: 'User',
        provideCodeStatus: 'ProvideCodeStatus',
      },
      truckSchedule: {
        fromHub: 'FromHub',
        toHub: 'ToHub',
        truckScheduleStatus: 'TruckScheduleStatus',
        truck: 'Truck',
      },
      truckScheduleDetail: {
        hub: 'Hub',
        truckScheduleStatus: 'TruckScheduleStatus',
      },
      uploadExcelHistory: {
        user: 'User',
      },
    },
  },
  pages: {
    login: {
      name: 'Đăng nhập',
      alias: 'user/login',
      hidden: true,
    },
    page404: {
      name: 'Không tìm thấy trang',
      alias: '404',
    },
    page403: {
      name: 'Không có quyền truy cập',
      alias: '403',
    },
    maintenancePage: {
      name: 'Bảo trì hệ thống',
      alias: 'bao-tri',
    },
  },
};
